[package]
name = "plexi_cli"
description = "A flexible auditor companion client"
version = "0.0.1"
authors = ["Thibault Meunier <thibault@cloudflare.com>"]
edition = "2021"
readme = "README.md"
homepage = "https://github.com/cloudflare/plexi"
repository = "https://github.com/thibmeu/plexi"
keywords = ["transparency", "e2ee", "auditor", "cryptography", "cli"]
categories = ["cryptography"]
license = "Apache-2.0"

[[bin]]
name = "plexi"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
clap-verbosity-flag = "2.2.0"
ed25519-dalek = { workspace = true }
env_logger = "0.11.3"
hex = { workspace = true, features = ["serde"] }
plexi_core = { path = "../plexi_core" }
serde_json = { workspace = true }
