[package]
name = "plexi_core"
description = "A flexible auditor companion client"
version = "0.0.1"
authors = ["Thibault Meunier <thibault@cloudflare.com>"]
edition = "2021"
readme = "../README.md"
homepage = "https://github.com/cloudflare/plexi"
repository = "https://github.com/thibmeu/plexi"
keywords = ["transparency", "e2ee", "auditor", "cryptography"]
categories = ["cryptography"]
license = "Apache-2.0"

[dependencies]
bincode = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = "1.0.61"
uuid = { workspace = true, features = ["v4", "serde"] }
